### ISSUE TITLE
Param to have the easy fast solution for debugging

### ISSUE THREAD

**Issue by ommmid** [ommmid/supertoroid_paper#1]
what is the param that leads to a fast convergence? is the following supposed to that?
https://github.com/ommmid/supertoroid_paper/blob/main/config/STparameters.yaml

**Comment by albarebecucha** [comment]
Fast convergence when all extrinsic parameters are set to zero (as these are not fully included in the optimization yet). Try that.

**Comment by albarebecucha** [comment]
I mean zero displacement.... identity rotation, zero translation.

**Comment by albarebecucha** [comment]
To make debugging quicker, while there is no change in orientation, you can disable three-times repeated calculations by making the index go from 0 to 0.

**Comment by ommmid** [comment]
isn't it set to zero displacement already in that yaml file? if that yaml file is not the correct place, would you lead me to where these extinsic params are set? I need a version of this package that runs successfully. Can you run this package with fast convergence in your computer?

**Comment by albarebecucha** [comment]
Most of the sets of parameters give good convergence, I am not sure why the current values don´t. Of course if initial conditions are equal to values, the convergence is assured.  
This is what I did for fast convergence:
1- in fit(), let the for loop run only once: for(int i=0,i<1;++i) (once we fix the issue of the PCA, we can change this back)
2- in the yaml file, use the following parameters (it should take about 5 seconds to give a result):
#Parameters for sampling the supertoroid
par_a1: 3
par_a2: 2
par_a3: 2
par_a4: 4
par_e1: 0.8
par_e2: 1.2 
par_x: 0.0
par_y: 0.0
par_z: 0.0
par_orx: 0.0
par_ory: 0.0
par_orz: 0.0

#Parameters for initial conditions of the solver
par_a10: 3
par_a20: 2
par_a30: 2
par_a40: 4
par_e10: 0.8
par_e20: 1.2
par_x0: 0.0
par_y0: 0.0
par_z0: 0.0
par_orx0: 0.0
par_ory0: 0.0
par_orz0: 0.0

**Comment by ommmid** [comment]
with this new parameters, it takes about `Time in ms 218701`, about 3 and a half mins

![supert](https://user-images.githubusercontent.com/26231820/216781408-48d462c3-1155-481f-a9e9-255d9987c58a.gif)

**Comment by albarebecucha** [comment]
Omid, this is strange, it takes 6 seconds in my computer. In addition, your  result is not a perfect fit, in mine both are exact. What should I do? Commit my code?
Oh wait... I assume you run the sampling launch file first? Otherwise the IC and your supertoroid will not coincide. Also make sure it is in the /tmp folder or whatever you are reading it from (I am sure you are doing this well, but just in case...)

**Comment by ommmid** [comment]
right, there is something wrong here. If your code works fine and gets result in 6 second in your computer, please commit it to this repo. Or just send it to me and I will do it.

**Comment by ommmid** [comment]
resolved at tag `v1.0`
