### ISSUE TITLE
is this calculation correct?

### ISSUE THREAD

**Issue by ommmid** [ommmid/supertoroid_paper#3]
After I have a set of param that runs fast for debugging, I can validate this myself but just put a note, this calculation seems wrong to me:

https://github.com/ommmid/supertoroid_paper/blob/35d826ff7e5633561db2746b3c8358b384ae17e6/src/supertoroid/st_fitting.cpp#L60

**eigenVectors** gets updated at line 60 and is not the same as the original **eigenVectors** anymore, so at line 61, the right hand side **eigenVectors** does not hold the original column.

For example:  if ```eigenVectors = [u, v, w]``` and we decide the second index, i.e. 1, to be the x-axis
```
pre_aligne_axis_ = 1
eigenVectors.col(0) = eigenVectors.col(1)

```
results in 
```
eigenVectors = [v, v, w]
```
Then
```eigenVectors.col(1) = eigenVectors.col(2)```
results in ```eigenVectors = [v, w, w]```

And finally,
```eigenVectors.col(2) = eigenVectors.col(0)``` results in ```eigenVectors = [v, w, v]```

while we wanted ```[v,w,u]```

**Comment by albarebecucha** [comment]
pre_align_axis is set to axis 2 (z) by default in the code. 
are you referring to preAlign lines 58 on? Please feel free to check debugging and modify if wrong. I see there is a commented auxiliar vector that may help to fix this issue.

**Comment by ommmid** [comment]
it is set o 2 by default but in `fit()` function it is set to 0, 1, 2:[ here](https://github.com/ommmid/supertoroid_paper/blob/35d826ff7e5633561db2746b3c8358b384ae17e6/src/supertoroid/st_fitting.cpp#L120)
The only case, that code works is if `pre_align_axis_` is equal to 0. I will fix it but the code does not finish the run for `i=0` because it gets stuck and does not converge

**Comment by albarebecucha** [comment]
As I commented in the other issue, the fastest way to do it for now is to set the for loop to run only once at fit(), and keeping per_align_axis set to 2. Because, if the extrinsics are set to the identity, the sampling node will generate a supertoroid with the z axes in the hole. 
Then we can fix this issue, in which I think you are correct, we need to use the auxiliary vector to keep the info of the first axis.

**Comment by ommmid** [comment]
corrected [at this commit](https://github.com/ommmid/supertoroid_paper/commit/9fa882e8c5c32b3d5a377119a24439bd7246c8b7)
